[package]
name         = "qv-mempool"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true
description  = "Clear + encrypted mempool, threshold Kyber decryption, batcher logic."

[lints]
workspace = true

[dependencies]
qv-common  = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }
serde      = { workspace = true }
qv-core    = { path = "../qv-core" }
qv-crypto  = { path = "../qv-crypto" }
dashmap    = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
